### ISSUE TITLE
Assembler duplicates labelled-tails needlessly

### ISSUE THREAD

**Issue by dalnefre** [organix/uFork#122]
When a chain of code (or data) cells has embedded labels, the assembler creates needless duplicates rather than sharing the labelled tails. Since the cells are read-only, this duplication of not easy to observe. However, the `nth` instruction can expose this behavior. The nth-tail should match the embedded labels, not just in denoted value, but in identity.

In the playground [this code example](https://ufork.org/playground/?dev=rom&text=H4sIAAAAAAAAE52VTW6DMBCF9z7FSNkkC1CBJE1CpagnQQbcxKr5EeNI7e2rAZpgMCV1dg6P7zH2m3EM74iiSJVoIL/VSmZcCwTFU6GUyD3NpUIohciVQFTfjKVVpU9g/8WQwJsHCaNFfcMrKInaexmJ1uFrBLvtHg7BcdNpeaMhsAHXvzoIX6NWyxFFo2k5q11itrzddj/k0bs23RJrQ45D0CE4TkVDwaqUaiTwvH9vWamvYKrmtb3xhOxsbNkKiJ84IUc77+9oTGoMDJ2jaWitcTk1rjVa/IYRHNYXGhpHw9Hh9NrlMLvWZ/Ebd0aLiwyBo9vWWtzqbPTheSJwrc1i97xbIz4gq4pCasbi++iFnGsOEh9jOfd9n3VfZR/A9skqm0RDsF8FgdkW1K1dt8zSZkhhaAaQeqLL5SzJQoki86QpeV0AZimb+37RDKXdyqpc9JcUbwRwhdVow7Ib6gRFmVuoMRR4aZkFXmaGGj0hBiNGUuDF9nUDGS1Jahta7ZGjLD+TVFztnP4C7fJwamkE6/OBuqoff9KKMV981VXTGdPlzH4AuFex7dQHAAA%3D) demonstrates the issue. The assertions should pass, but they currently do not.

**Comment by jamesdiacono** [comment]
I'm on it.
